[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
evm_version = 'shanghai'

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
blast = "https://rpc.ankr.com/blast"
optimism = "https://optimism.llamarpc.com"
fantom = "https://fantom-pokt.nodies.app"
arbitrum =  "https://arb1.arbitrum.io/rpc" # https://arbitrum.llamarpc.com
bsc = "https://binance.llamarpc.com"
moonriver = "https://moonriver.public.blastapi.io"
gnosis = "https://gnosis-mainnet.public.blastapi.io"
avalanche = "https://avax.meowrpc.com"
polygon = "https://rpc.ankr.com/polygon"
celo = "https://rpc.ankr.com/celo"
base = "https://developer-access-mainnet.base.org"
linea = "https://linea.drpc.org"
mantle = "https://rpc.mantle.xyz"
sei = "wss://sei.drpc.org"

# See more config options https://github.com/foundry-rs/foundry/tree/master/.config

[fmt]
line_length = 120
tab_width = 4
bracket_spacing=false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = 'preserve'
variable_override_spacing = true
wrap_comments = false
ignore = []



